apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: test-env-rs
  labels:
    env: test
spec:
  replicas: 3
  selector:
    matchLabels:
      env: test
  template:
    metadata:
      labels:
        env: test
    spec:
      containers:
      - image: nginx
        name: nginx-app
