controller:
  service:
    type: NodePort
    nodePorts:
      http: 30070
      https: 30443
  replicaCount: 2
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
